version: "3"
services:
  pitch:
    image: gitpitch/desktop:pro
    volumes:
      - ./:/repo
    ports:
      - 9000:9000

  functions:
    build:
      context: ./functions
    environment:
      SLACK_API_TOKEN: ${SLACK_API_TOKEN}
      SLACK_SLASH_TOKEN_PREPARE: ${SLACK_SLASH_TOKEN_PREPARE}
      SLACK_SLASH_TOKEN_PRESENTER: ${SLACK_SLASH_TOKEN_PRESENTER}
      FIREBASE_CONFIG: /root/.config/gcloud/application_default_credentials.json
    volumes:
      - ./:/app
      - $HOME/.config/gcloud:/root/.config/gcloud:ro
      - functions_node_modules:/app/functions/node_modules

  scripts:
    build:
      context: ./scripts
    environment:
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
    volumes:
      - ./:/src
      - scripts_node_modules:/app/scripts/node_modules

volumes:
  scripts_node_modules:
    driver: local
  functions_node_modules:
    driver: local
